<?php

/**
 * KeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KeyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Key');
    }
}