<?php

/**
 * MachineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MachineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MachineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Machine');
    }
}