<?php

/**
 * PoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pool');
    }
}