<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('key', 'key_pool_id_product_id');
        $this->createForeignKey('key', 'key_product_id_product_id', array(
             'name' => 'key_product_id_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             ));
        $this->addIndex('key', 'key_product_id', array(
             'fields' =>
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('key', 'key_pool_id_product_id', array(
             'name' => 'key_pool_id_product_id',
             'local' => 'pool_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             ));
        $this->dropForeignKey('key', 'key_product_id_product_id');
        $this->removeIndex('key', 'key_product_id', array(
             'fields' =>
             array(
              0 => 'product_id',
             ),
             ));
    }
}
