<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('pool', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' =>
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'version' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('product', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'metaname' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '255',
             ),
             'description' =>
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'packge' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'version' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('pool_version', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'name' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' =>
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'version' =>
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
              1 => 'version',
             ),
             ));
        $this->createTable('product_version', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'name' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'metaname' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' =>
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'packge' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'version' =>
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
              1 => 'version',
             ),
             ));
        $this->removeColumn('key', 'product');
        $this->removeColumn('machine', 'key_id');
        $this->removeColumn('key_version', 'product');
        $this->removeColumn('machine_version', 'key_id');
        $this->addColumn('key', 'product_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('key', 'machine_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('key', 'buyer_id', 'integer', '8', array(
             ));
        $this->addColumn('key', 'pool_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('key_version', 'product_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('key_version', 'machine_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('key_version', 'buyer_id', 'integer', '8', array(
             ));
        $this->addColumn('key_version', 'pool_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('key', 'name', 'string', '255', array(
             'notnull' => '1',
             'unique' => '1',
             ));
        $this->changeColumn('machine', 'name', 'string', '255', array(
             'notnull' => '1',
             'unique' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('pool');
        $this->dropTable('product');
        $this->dropTable('pool_version');
        $this->dropTable('product_version');
        $this->addColumn('key', 'product', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('machine', 'key_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('key_version', 'product', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('machine_version', 'key_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->removeColumn('key', 'product_id');
        $this->removeColumn('key', 'machine_id');
        $this->removeColumn('key', 'buyer_id');
        $this->removeColumn('key', 'pool_id');
        $this->removeColumn('key_version', 'product_id');
        $this->removeColumn('key_version', 'machine_id');
        $this->removeColumn('key_version', 'buyer_id');
        $this->removeColumn('key_version', 'pool_id');
    }
}
