<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('product', 'packge');
        $this->removeColumn('product_version', 'packge');
        $this->addColumn('product', 'package', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('product_version', 'package', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('product', 'packge', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('product_version', 'packge', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->removeColumn('product', 'package');
        $this->removeColumn('product_version', 'package');
    }
}