<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('pool', 'pool_buyer_id_sf_guard_user_id', array(
             'name' => 'pool_buyer_id_sf_guard_user_id',
             'local' => 'buyer_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('pool', 'pool_buyer_id', array(
             'fields' =>
             array(
              0 => 'buyer_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('pool', 'pool_buyer_id_sf_guard_user_id');
        $this->removeIndex('pool', 'pool_buyer_id', array(
             'fields' =>
             array(
              0 => 'buyer_id',
             ),
             ));
    }
}
