<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('pool', 'buyer_id', 'integer', '8', array(
             'notnull' => '1',
             'default' => '1',
             ));
        $this->addColumn('pool_version', 'buyer_id', 'integer', '8', array(
             'notnull' => '1',
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('pool', 'buyer_id');
        $this->removeColumn('pool_version', 'buyer_id');
    }
}
