<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('key', 'machine_id', 'integer', '8', array(
             ));
        $this->changeColumn('key_version', 'machine_id', 'integer', '8', array(
             ));
    }

    public function down()
    {

    }
}
