Key:
  actAs:
    - Timestampable
    - Signable
    - Versionable
  columns:
    name:
      type: string(255)
      notnull: true
    product:
      type: string(255)
      notnull: true
  relations:
    Machines:
      class: Machine
      local: id
      foreign: key_id
      type: many

Machine:
  actAs:
    - Timestampable
    - Signable
    - Versionable
  columns:
    key_id:
      type: integer
      notnull: true
    name:
      type: string(255)
      notnull: true
